---
# use atomic-installer advanced method. (https://docs.openshift.com/enterprise/3.2/install_config/install/advanced_install.html)

- name: Curl get pip
  become: yes
  command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" chdir=/home/ec2-user
  tags:
   - atomic

- name: Python install pip
  become: yes
  command: python /home/ec2-user/get-pip.py chdir=/home/ec2-user  
  tags:
   - atomic

- name: Install passlib
  become: yes
  pip: name=passlib state=present
  tags:
   - atomic


# - name: Copy over id_rsa key 
#   copy: dest="/home/ec2-user/.ssh/id_rsa"  mode=0400  src="{{ terraform_working_dir }}/id_rsa" 

  
# - name: Run atomic installer (advanced method) ansible-playbook 
#   shell: ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory_ose /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml chdir=/home/ec2-user  
#   tags:
#    - atomic 

# - name: Set a password for admin
#   become: yes
#   htpasswd: name=admin  password=Containers!  path=/etc/origin/master/htpasswd  state=present 
#   tags:
#    - atomic