---

- name: disable all repos by default
  shell: subscription-manager repos --disable="*"
  tags:
    - rhel

- name: Enable the requisite rhel7 repos
  shell: subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-7-server-ose-3.2-rpms"
  tags:
    - rhel

- name: Import keys
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-beta
  tags:
    - rhel

- name: Install pre requisites
  yum: name={{ item }} state=present
  with_items:
      - wget
      - vim
      - git
      - unzip
      - net-tools
      - bind-utils
      - bridge-utils
      - bash-completion
      - iptables-services
  tags:
    - rhel

- name: Update all yum packages
  yum: name=* state=latest
  tags:
    - rhel

- name: Install atomic-openshift-utils
  yum: name=atomic-openshift-utils state=present
  tags:
    - rhel


- name: Install Docker
  yum: name=docker-1.10.3 state=present
  tags:
    - rhel

- name: Start docker
  service: name=docker state=started enabled=yes
  tags:
    - rhel

- name: Enable insecure registry
  lineinfile: dest=/etc/sysconfig/docker state=present line='OPTIONS=--insecure-registry 172.30.0.0/16' regexp="^#?OPTIONS" 
  tags:
    - rhel

- name: Setup docker-storage-setup
  command: echo -e "DEVS=/dev/xvdb\nVG=docker-vg" >> /etc/sysconfig/docker-storage-setup
  tags:
    - rhel

- name: get EC2 Facts
  action: ec2_facts
  
# - debug: var=hostvars

- name: Template the inventory file to nodes
  template: dest=/home/ec2-user/inventory_ose  src=inventory_ose.j2
  tags:
   - rhel 
